### ISSUE TITLE
Do not display stacktrace (production mode)

### ISSUE THREAD

**Issue by 4n70w4** [padiazg/barcode-generator#3]
Example incorrect bcid: `bcid=qr&text=123456789012&backgroundcolor=FFFFFF&paddingwidth=2&paddingheight=2&includetext`

Output:
```
Error: bwipp.unknownEncoder: qr
    at /app/node_modules/bwip-js/bwipp.js:27935:10
    at Function.module.exports.toBuffer (/app/node_modules/bwip-js/node-bwipjs.js:151:10)
    at module.exports (/app/node_modules/bwip-js/node-bwipjs.js:56:17)
    at app.get (/app/index.js:12:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
```

**Comment by padiazg** [comment]
Good point. Will see a better way to display errors.
